const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-addressbook",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"收货地址",
                        "menuJump":"列表",
                        "tableName":"address"
                    }
                ],
                "menu":"收货地址"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"防护知识",
                        "menuJump":"列表",
                        "tableName":"fanghuzhishi"
                    }
                ],
                "menu":"防护知识"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"防护知识收藏",
                        "menuJump":"列表",
                        "tableName":"fanghuzhishiCollection"
                    }
                ],
                "menu":"防护知识收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"防护知识留言",
                        "menuJump":"列表",
                        "tableName":"fanghuzhishiLiuyan"
                    }
                ],
                "menu":"防护知识留言"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"检测记录",
                        "menuJump":"列表",
                        "tableName":"jiance"
                    }
                ],
                "menu":"检测记录"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-activity",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告通知",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告通知"
            }
			,
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"新冠抗原",
                        "menuJump":"列表",
                        "tableName":"xinguankangyuan"
                    }
                ],
                "menu":"新冠抗原"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"新冠抗原收藏",
                        "menuJump":"列表",
                        "tableName":"xinguankangyuanCollection"
                    }
                ],
                "menu":"新冠抗原收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"新冠抗原留言",
                        "menuJump":"列表",
                        "tableName":"xinguankangyuanLiuyan"
                    }
                ],
                "menu":"新冠抗原留言"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-order",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"新冠抗原订单",
                        "menuJump":"列表",
                        "tableName":"xinguankangyuanOrder"
                    }
                ],
                "menu":"新冠抗原订单"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
